### ISSUE TITLE
No compatible templates on Rancher 1.6.27

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/kartoza-rancher-catalogue#101]
I tried to add Geonode in Rancher 1.6.27, I saw your catalogue so I added it in my Rancher with branch `master` and `develop` but I have this:
![kartoza-catalog](https://user-images.githubusercontent.com/12623986/58914853-3fc7a180-8728-11e9-9e44-a1873f255a31.png)

**Comment by NyakudyaA** [comment]
@Fanevanjanahary forgot to respond to you, I hope you have figured this out right. You basically need to run through the whole process of adding a host on your machine and then deploy the catalog.
https://discoposse.com/2015/11/09/rancher-part-2-adding-a-docker-host-to-rancher or https://rancher.com/docs/rancher/v1.6/en/

**Comment by Fanevanjanahary** [comment]
@NyakudyaA, I think that It was my networking. When I had good Internet this morning I could see all templates even thought there is no host. Thank you for your help.
